#!/usr/bin/env bash
#
# xargs0 - shell "alias" for xargs --no-run-if-empty -0
#
# Copyright (c) 2006,2023,2025 by Landon Curt Noll.  All Rights Reserved.
#
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby granted,
# provided that the above copyright, this permission notice and text
# this comment, and the disclaimer below appear in all of the following:
#
#       supporting documentation
#       source copies
#       source works derived from this source
#       binaries derived from this source or from derived source
#
# LANDON CURT NOLL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL LANDON CURT NOLL BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
# USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# chongo (Landon Curt Noll) /\oo/\
#
# http://www.isthe.com/chongo/index.html
# https://github.com/lcn2
#
# Share and enjoy!  :-)


# export VERSION="1.0.0 2025-03-23"


# test of xargs has --no-run-if-empty
#
xargs --no-run-if-empty true < /dev/null > /dev/null 2>&1
export HAS_NO_RUN_IF_EMPTY="$?"


# prefer xargs with --no-run-if-empty
#
if [[ $HAS_NO_RUN_IF_EMPTY -eq 0 ]]; then
    xargs -0 --no-run-if-empty "$@"
else
    xargs -0 "$@"
fi
